apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-cm
  namespace: bankapp-ns
data:
  MYSQL_DATABASE: bankappdb
  MYSQL_USER: root
  MYSQL_HOST: mysql-svc
  MYSQL_PORT: "3306"
  OLLAMA_URL: http://localhost:11434