kind: Service
apiVersion: v1

metadata:
  name: mysql-svc
  namespace: bankapp-ns
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  type: ClusterIP

---

kind: Service
apiVersion: v1
metadata:
  name: bankapp-svc
  namespace: bankapp-ns
spec:
  selector:
    app: bankapp
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort